name: 'Hostme Deploy Action'
icon: upload-cloud
color: purple
description: 'Deployment action for Hostme.spaces'
inputs:
  project-zip:
    description: 'Your hostme.space zip project to upload on Hostme.Spaces'
    required: true
    default: 'oss-is-the-best.zip'
  hostme-project-name:
    description: 'Your hostme project name on Hostme.Spaces'
    required: true
    default: 'oss-is-the-best'
  hostme-api-token:
    description: 'Your hostme.space API Token.'
    required: true
    default: 'not-real-token'
  commands:
    description: 'Commands you want to execute before the upload on hostme.Space'
    required: false
    default: |
      echo Hostme-action deploying process...
      echo example of command 2
runs:
  using: "composite"
  steps:
    # We run all inputs commands you provided here
    # before uploading the zip on hostme.space
    - run: |
        ${{ inputs.commands }}
      shell: bash
    # We upload your zip project using deploy.sh
    - run: |
        echo [-] Deployment in progress...
        
        ${{ github.action_path }}/deploy.sh ${{ inputs.project-zip }} ${{ inputs.hostme-project-name }} '${{ inputs.hostme-api-token }}'
        
        echo [-] Deployed successfully !
      shell: bash
